feat: support cx355001 fan
kongo09/philips-airpurifier-coap pull request #144
Opened 2024-07-14 16:40 UTC by EuleMitKeule

This PR adds support for the new CX3550/01 fan.
All features are working, including power cycling, speed mode selection, oscillation and timer.

2024-08-18 16:24 UTC, kongo09 commented
Thanks a lot for your great work. If you could help out with the suggested adaptations above, I can merge it in. It's great to have others contribute and take some of the load!

2024-08-19 01:41 UTC, EuleMitKeule commented
I am not able to see any suggestions. Also, I believe there are still some bugs, therefore I will convert this PR to a draft for now.
![grafik](https://github.com/user-attachments/assets/24b3b794-6f17-43ee-ae39-5396e32b5fe3)

2024-08-19 07:18 UTC, kongo09 commented
Don't you see the comments I've left?

2024-08-19 07:20 UTC, kongo09 requested changes
Sorry, I forgot to submit the review

2024-08-19 07:20 UTC, kongo09 commented on README.md
> +- CX3550/01
You should be able to leave out the `/01` as this is (most of the time) only a model variant by Philips referring to color of the casing or region of sales. Ideally, all CX3550 models should work and the integration will pick that up.

2024-08-19 07:20 UTC, kongo09 commented on custom_components/philips_airpurifier_coap/const.py
> +    CX3550 = "CX3550/01"
please leavel out the `/01` as discussed above

2024-08-19 07:20 UTC, kongo09 commented on custom_components/philips_airpurifier_coap/philips.py
> +    def oscillating(self) -> bool | None:
This property is already part of `PhilipsGenericCoAPFanBase` with the difference of the `on` test. I suggest you put the special test into that location. It's all not perfect, but I rather avoid the code duplication.

2024-08-19 07:20 UTC, kongo09 commented on custom_components/philips_airpurifier_coap/philips.py
> +    async def async_oscillate(self, oscillating: bool) -> None:
Again, I'd prefer if we kept the code in one place and the class is only used to configure. I see that you did a bit more work here. Do you think you can merge that with the existing code in `PhilipsGenericCoAPFanBase`?

2024-10-05 20:06 UTC, kongo09 commented
@EuleMitKeule will you continue to work on this?

2024-10-05 21:43 UTC, EuleMitKeule commented
I might, got not much time currently.

2024-10-05 21:46 UTC, kongo09 commented
I know that problem ;-)

I also noticed that you did some bigger changes in your fork. Looks interesting but certainly requires a bit of thinking to pull that over. Thanks for engaging with the code that much and helping out!

Just let me know when you find more time - I might pull in your code for the CX model in the meantime.

2024-10-05 23:22 UTC, EuleMitKeule commented
Yeah, I had some problem getting the integration to work at all, that's why I started to make some larger changes to the code. Controlling the fan in the fork is working for me, but displaying the state is still bugged.

2024-10-26 14:03 UTC, merged

2024-10-26 15:48 UTC, kongo09 commented
I've done above changes after merging.